"""
TONES Fashion - LLM Adapter

Purpose:
    Convert retrieved RAG context into a customer-facing answer.

Providers:
    - mock
    - openrouter

Architecture:

    Customer Query
          ↓
    RAG Context Builder
          ↓
    RAG Prompt
          ↓
    LLM Adapter
          ↓
    OpenRouter
          ↓
    Selected Model
          ↓
    Response Quality Guard
          ↓
    Customer Answer
"""

import os
import re
import requests
from abc import ABC, abstractmethod


# ============================================================
# BASE LLM ADAPTER
# ============================================================

class LLMAdapter(ABC):
    """
    Provider-independent interface.
    """

    @abstractmethod
    def generate(
        self,
        system_prompt: str,
        user_prompt: str,
    ) -> str:
        """
        Generate a response from the LLM.
        """
        raise NotImplementedError


# ============================================================
# MOCK ADAPTER
# ============================================================

# ============================================================
# MOCK ADAPTER
# ============================================================

# ============================================================
# MOCK ADAPTER
# ============================================================

class MockLLMAdapter(LLMAdapter):
    """
    Development-only deterministic LLM adapter.

    This adapter does not call an external AI provider.

    It reads the actual RAG prompt generated by the project
    and creates a simple customer-facing response.

    Supported development routes:
        PRODUCT
        BUSINESS
        MIXED
        GENERAL
    """

    def generate(
        self,
        system_prompt: str,
        user_prompt: str,
    ) -> str:

        import json
        import re

        # ====================================================
        # 1. EXTRACT CUSTOMER QUERY
        # ====================================================

        query_match = re.search(
    r"(?:CUSTOMER QUERY|CUSTOMER QUESTION)\s*-+\s*(.*?)"
    r"\s*(?:RETRIEVED KNOWLEDGE|TONES FASHION INFORMATION)",
    user_prompt,
    re.DOTALL | re.IGNORECASE,
)

        if query_match:
            query = query_match.group(1).strip()

        query_lower = query.lower()

        # ====================================================
        # 2. EXTRACT RETRIEVED JSON CONTEXT
        # ====================================================

        context = {}

        knowledge_match = re.search(
    r"(?:RETRIEVED KNOWLEDGE|TONES FASHION INFORMATION)\s*-+\s*",
    user_prompt,
    re.IGNORECASE,
)
        if knowledge_match:

            json_start = knowledge_match.end()

            json_text = user_prompt[
                json_start:
            ].lstrip()

            # Find the first JSON object.
            first_brace = json_text.find("{")

            if first_brace >= 0:

                json_text = json_text[
                    first_brace:
                ]

                try:

                    decoder = json.JSONDecoder()

                    context, _ = decoder.raw_decode(
                        json_text
                    )

                except json.JSONDecodeError:

                    context = {}

        # ====================================================
        # 3. READ ROUTE
        # ====================================================

        route = str(
            context.get(
                "route",
                "",
            )
        ).upper().strip()

        # ====================================================
        # 4. READ RETRIEVED DATA
        # ====================================================

        products = context.get(
            "products",
            [],
        )

        business_knowledge = context.get(
            "business_knowledge",
            [],
        )

        # Retrieval metadata supplied by the RAG context builder.
        business_intent = str(
            context.get("business_intent", "")
        ).lower().strip()

        special_operation = str(
            context.get("special_operation", "")
        ).upper().strip()

        attribute_type = str(
            context.get("attribute_type", "")
        ).upper().strip()

        if not isinstance(
            products,
            list,
        ):
            products = []

        if not isinstance(
            business_knowledge,
            list,
        ):
            business_knowledge = []

        # ====================================================
        # 5. BUSINESS KNOWLEDGE FINDER
        # ====================================================

        def find_business(
            topics,
        ):

            for item in business_knowledge:

                if not isinstance(
                    item,
                    dict,
                ):
                    continue

                topic = str(
                    item.get(
                        "topic",
                        "",
                    )
                ).lower().strip()

                if topic in topics:

                    return item

            return None

        # ====================================================
        # 6. FACT FORMATTER
        # ====================================================

        def get_facts(
            item,
        ):

            if not item:
                return []

            facts = item.get(
                "facts",
                [],
            )

            if not isinstance(
                facts,
                list,
            ):
                return []

            return [
                str(fact).strip()
                for fact in facts
                if str(fact).strip()
            ]

        # ====================================================
        # 7. PRODUCT RESPONSE
        # ====================================================

        def product_answer():

            if not products:

                return (
                    "I couldn't find a matching product "
                    "in the current TONES Fashion knowledge."
                )

            lines = [
                "Here are the matching TONES Fashion products:"
            ]

            shown = 0

            for product in products[:6]:

                if not isinstance(
                    product,
                    dict,
                ):
                    continue

                # RAG product records use "title".
                # API response mapping may use "name".
                name = str(
                    product.get(
                        "title",
                        product.get(
                            "name",
                            "",
                        ),
                    )
                ).strip()

                price = product.get(
                    "price"
                )

                currency = str(
                    product.get(
                        "currency",
                        "INR",
                    )
                )

                if not name:
                    continue

                if price is not None:

                    try:

                        price_text = (
                            f"{currency} "
                            f"{float(price):,.0f}"
                        )

                    except (
                        TypeError,
                        ValueError,
                    ):

                        price_text = (
                            f"{currency} {price}"
                        )

                else:

                    price_text = (
                        "Price not available"
                    )

                lines.append(
                    f"- {name} - {price_text}"
                )

                shown += 1

            if shown == 0:

                return (
                    "I couldn't find a matching product "
                    "in the current TONES Fashion knowledge."
                )

            lines.append("")

            lines.append(
                "The product cards below show the "
                "available product details."
            )

            lines.append(
    "Recorded in-stock sizes come from the "
    "current knowledge snapshot. Live inventory "
    "availability is not confirmed."
)

            return "\n".join(
                lines
            )
        

        # ====================================================
        # 8. RETURN POLICY RESPONSE
        # ====================================================

        def return_answer():

            item = find_business(
                {
                    "return_exchange_policy",
                }
            )

            facts = get_facts(
                item
            )

            if not facts:

                return (
                    "Return and exchange information is "
                    "currently unavailable or unverified."
                )

            return (
                "Here is the TONES Fashion "
                "return and exchange policy:\n\n"
                + "\n".join(
                    f"- {fact}"
                    for fact in facts
                )
            )

        # ====================================================
        # 9. SHIPPING RESPONSE
        # ====================================================

        def shipping_answer():

            item = find_business(
                {
                    "shipping_policy",
                }
            )

            facts = get_facts(
                item
            )

            if not facts:

                return (
                    "Shipping information is currently "
                    "unavailable or unverified."
                )

            return (
                "Here is the current TONES Fashion "
                "shipping information:\n\n"
                + "\n".join(
                    f"- {fact}"
                    for fact in facts
                )
            )

        # ====================================================
        # 10. ORDER TRACKING RESPONSE
        # ====================================================

        def tracking_answer():

            item = find_business(
                {
                    "order_tracking",
                }
            )

            facts = get_facts(
                item
            )

            if not facts:

                return (
                    "Order tracking information is "
                    "currently unavailable or unverified."
                )

            return (
                "You can track your TONES Fashion order "
                "using the available tracking service:\n\n"
                + "\n".join(
                    f"- {fact}"
                    for fact in facts
                )
            )

        # ====================================================
        # 11. PAYMENT / COD RESPONSE
        # ====================================================

        def payment_answer():

            item = find_business(
                {
                    "payment_methods",
                }
            )

            if not item:

                return (
                    "Payment information is currently "
                    "unavailable or unverified."
                )

            status = str(
                item.get(
                    "status",
                    "",
                )
            ).upper().strip()

            if status == "NEEDS_VERIFICATION":

                return (
                    "Cash on Delivery (COD) is not "
                    "currently confirmed in the available "
                    "TONES Fashion knowledge."
                )

            facts = get_facts(
                item
            )

            if not facts:

                return (
                    "Payment information is currently "
                    "unavailable or unverified."
                )

            return (
                "Here is the available TONES Fashion "
                "payment information:\n\n"
                + "\n".join(
                    f"- {fact}"
                    for fact in facts
                )
            )

        # ====================================================
        # 12. SPECIAL PRODUCT OPERATIONS
        # ====================================================

        # These operations use already-retrieved structured product
        # facts. They do not invent or duplicate catalog information.
        special_intent = str(
            context.get("special_intent", "")
        ).upper().strip()

        special_operation = str(
            context.get("special_operation", "")
        ).upper().strip()

        operation = special_intent or special_operation

        def numeric_price(product):
            try:
                value = product.get("price")
                if value is None:
                    return None
                return float(value)
            except (TypeError, ValueError, AttributeError):
                return None

        def one_product_answer(product, label):
            if not isinstance(product, dict):
                return None

            name = str(
                product.get("title", product.get("name", ""))
            ).strip()
            price = numeric_price(product)

            if not name or price is None:
                return None

            currency = str(product.get("currency", "INR")).strip()
            return f"{label}: {name} - {currency} {price:,.0f}."

        # If the retrieval layer supplies a special operation, honor it.
        # The query-word fallback also keeps the mock adapter useful while
        # the routing/context layers are being migrated.
        if operation == "CHEAPEST_PRODUCT" or "cheapest" in query_lower:
            valid = [
                p for p in products
                if isinstance(p, dict) and numeric_price(p) is not None
            ]

            if valid:
                minimum_price = min(
                    numeric_price(product)
                    for product in valid
                )

                cheapest_products = [
                    product
                    for product in valid
                    if numeric_price(product) == minimum_price
                ]

                lines = [
                    "The cheapest verified product(s) in the current "
                    "TONES Fashion catalog are:"
                ]

                for product in cheapest_products:
                    name = str(
                        product.get(
                            "title",
                            product.get("name", "Unknown product")
                        )
                    ).strip()

                    currency = str(
                        product.get("currency", "INR")
                    ).strip()

                    lines.append(
                        f"- {name} - {currency} "
                        f"{minimum_price:,.0f}"
                    )

                return "\n".join(lines)

            return (
                "I couldn't determine the cheapest product from the "
                "currently retrieved TONES Fashion product data."
            )

        if operation == "MOST_EXPENSIVE_PRODUCT" or "most expensive" in query_lower:
            valid = [
                p for p in products
                if isinstance(p, dict) and numeric_price(p) is not None
            ]

            if valid:
                maximum_price = max(
                    numeric_price(product)
                    for product in valid
                )

                expensive_products = [
                    product
                    for product in valid
                    if numeric_price(product) == maximum_price
                ]

                lines = [
                    "The most expensive verified product(s) in the "
                    "current TONES Fashion catalog are:"
                ]

                for product in expensive_products:
                    name = str(
                        product.get(
                            "title",
                            product.get("name", "Unknown product")
                        )
                    ).strip()

                    currency = str(
                        product.get("currency", "INR")
                    ).strip()

                    lines.append(
                        f"- {name} - {currency} "
                        f"{maximum_price:,.0f}"
                    )

                return "\n".join(lines)

            return (
                "I couldn't determine the most expensive product from the "
                "currently retrieved TONES Fashion product data."
            )

        if operation == "PRODUCTS_ON_SALE" or "on sale" in query_lower:
            sale_products = []
            for product in products:
                if not isinstance(product, dict):
                    continue
                price = numeric_price(product)
                try:
                    compare_at = float(product.get("compare_at_price"))
                except (TypeError, ValueError):
                    continue
                if price is not None and compare_at > price:
                    sale_products.append((price, product))

            if not sale_products:
                return (
                    "I couldn't find any products with a verified sale price "
                    "in the current TONES Fashion knowledge."
                )

            sale_products.sort(key=lambda item: item[0])
            lines = ["Here are the TONES Fashion products with verified sale pricing:"]
            for _, product in sale_products[:6]:
                answer = one_product_answer(product, "•")
                if answer:
                    lines.append(answer)
            return "\n".join(lines)

        # Generic product-attribute questions need a product name before
        # an attribute can be answered safely.
        if operation in {
            "PRODUCT_FABRIC",
            "PRODUCT_SIZE",
            "PRODUCT_FIT",
            "PRODUCT_MATERIAL",
            "PRODUCT_ATTRIBUTE_CLARIFICATION",
        }:

            resolved_attribute = attribute_type or operation

            attribute = {
                "PRODUCT_FABRIC": "fabric",
                "PRODUCT_SIZE": "size",
                "PRODUCT_FIT": "fit",
                "PRODUCT_MATERIAL": "material",
            }.get(
                resolved_attribute,
                "product",
            )

            return (
                f"Which TONES Fashion product would you like to know the "
                f"{attribute} details for?"
            )

        # ====================================================
        # 13. MIXED QUERY
        #
        # IMPORTANT:
        # Process MIXED before individual business
        # branches so both parts are answered.
        # ====================================================

        if route == "MIXED":

            response_parts = []

            # ------------------------------------------------
            # PRODUCT PART
            # ------------------------------------------------

            if products:

                response_parts.append(
                    product_answer()
                )

            # ------------------------------------------------
            # RETURN PART
            # ------------------------------------------------

            if (
                "return" in query_lower
                or "exchange" in query_lower
            ):

                response_parts.append(
                    return_answer()
                )

            # ------------------------------------------------
            # SHIPPING PART
            # ------------------------------------------------

            if (
                "shipping" in query_lower
                or "delivery" in query_lower
                or "deliver" in query_lower
            ):

                response_parts.append(
                    shipping_answer()
                )

            # ------------------------------------------------
            # PAYMENT PART
            # ------------------------------------------------

            if (
                "cod" in query_lower
                or "cash on delivery" in query_lower
            ):

                response_parts.append(
                    payment_answer()
                )

            if response_parts:

                return "\n\n".join(
                    response_parts
                )

            return (
                "I can help with the supported TONES "
                "Fashion information available for "
                "your question."
            )

        # ====================================================
        # 13. PRODUCT ROUTE
        # ====================================================

        if route == "PRODUCT":

            return product_answer()

        # ====================================================
        # 14. BUSINESS ROUTE
        # ====================================================

        if route == "BUSINESS":

            # Return
            if (
                "return" in query_lower
                or "exchange" in query_lower
            ):

                return return_answer()

            # Shipping
            if (
                "shipping" in query_lower
                or "delivery" in query_lower
                or "deliver" in query_lower
            ):

                return shipping_answer()

            # Tracking
            if (
                "track my order" in query_lower
                or "track order" in query_lower
                or "order tracking" in query_lower
                or (
                    "track" in query_lower
                    and "order" in query_lower
                )
            ):

                return tracking_answer()

            # Payment / COD
            if (
                "cod" in query_lower
                or "cash on delivery" in query_lower
                or "payment" in query_lower
            ):

                return payment_answer()

            # Order cancellation
            #
            # Cancellation information is already covered by the verified
            # return/exchange knowledge. Reuse only the cancellation-related
            # fact instead of returning unrelated shipping information.
            if (
                business_intent == "order_cancellation"
                or "cancel my order" in query_lower
                or "cancel order" in query_lower
                or "cancellation" in query_lower
            ):

                cancellation_facts = []

                for item in business_knowledge:

                    if not isinstance(item, dict):
                        continue

                    facts = get_facts(item)

                    for fact in facts:

                        fact_lower = fact.lower()

                        if (
                            "orders can be cancelled" in fact_lower
                            or (
                                "cancel" in fact_lower
                                and "dispatch" in fact_lower
                            )
                        ):
                            cancellation_facts.append(fact)

                if cancellation_facts:
                    return (
                        "Here is the TONES Fashion order cancellation "
                        "information:\n\n"
                        + "\n".join(
                            f"- {fact}"
                            for fact in cancellation_facts
                        )
                    )

                return (
                    "The current TONES Fashion knowledge states that "
                    "orders can be cancelled only before dispatch."
                )

            # Generic business fallback
            if business_knowledge:

                item = business_knowledge[0]

                facts = get_facts(
                    item
                )

                if facts:

                    return (
                        "Here is the available TONES "
                        "Fashion information:\n\n"
                        + "\n".join(
                            f"- {fact}"
                            for fact in facts
                        )
                    )

            return (
                "I couldn't find verified information "
                "for that question in the current "
                "TONES Fashion knowledge."
            )

        # ====================================================
        # 15. GENERAL
        # ====================================================

        return (
            "I can help with TONES Fashion products, "
            "sizes, prices, shipping, returns, "
            "order tracking and payment information."
        )
# ============================================================
# OPENROUTER ADAPTER
# ============================================================

class OpenRouterLLMAdapter(LLMAdapter):
    """
    OpenRouter implementation of the LLM adapter.

    Environment variables:
        OPENROUTER_API_KEY
        OPENROUTER_MODEL

    Default model:
        openrouter/free
    """

    BASE_URL = "https://openrouter.ai/api/v1/chat/completions"

    def __init__(self):

        self.api_key = os.getenv(
            "OPENROUTER_API_KEY"
        )

        if not self.api_key:
            raise RuntimeError(
                "OPENROUTER_API_KEY environment variable is not set."
            )

        self.model = os.getenv(
            "OPENROUTER_MODEL",
            "openrouter/free",
        )

        self.timeout = int(
            os.getenv(
                "OPENROUTER_TIMEOUT",
                "60",
            )
        )

    def generate(
        self,
        system_prompt: str,
        user_prompt: str,
    ) -> str:

        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json",
        }

        payload = {
            "model": self.model,
            "messages": [
                {
                    "role": "system",
                    "content": system_prompt,
                },
                {
                    "role": "user",
                    "content": user_prompt,
                },
            ],
            "temperature": 0.2,
            "max_tokens": 800,
        }

        try:

            response = requests.post(
                self.BASE_URL,
                headers=headers,
                json=payload,
                timeout=self.timeout,
            )

        except requests.RequestException as exc:

            raise RuntimeError(
                f"OpenRouter request failed: {exc}"
            ) from exc

        if response.status_code != 200:

            try:
                error_data = response.json()

            except ValueError:
                error_data = response.text

            raise RuntimeError(
                "OpenRouter API request failed.\n"
                f"HTTP Status: {response.status_code}\n"
                f"Response: {error_data}"
            )

        try:

            data = response.json()

        except ValueError as exc:

            raise RuntimeError(
                "OpenRouter returned an invalid JSON response."
            ) from exc

        try:

            content = data["choices"][0]["message"]["content"]

        except (
            KeyError,
            IndexError,
            TypeError,
        ) as exc:

            raise RuntimeError(
                "OpenRouter response did not contain "
                "the expected assistant message."
            ) from exc

        if not content or not content.strip():

            raise RuntimeError(
                "OpenRouter returned an empty response."
            )

        return content.strip()


# ============================================================
# RESPONSE QUALITY GUARD
# ============================================================

def is_invalid_customer_response(response: str) -> bool:
    """
    Detect obvious internal classifications, internal metadata,
    or other responses that must never reach the customer.
    """

    if not response:
        return True

    text = response.strip().lower()

    # --------------------------------------------------------
    # INTERNAL CLASSIFICATION PATTERNS
    # --------------------------------------------------------

    forbidden_patterns = [
        "user safety:",
        "safety classification",
        "safety status:",
        "moderation result",
        "moderation classification",
        "moderation status:",
        "internal classification",
        "internal status:",
        "risk classification",
        "risk status:",
        "policy classification:",
        "classification:",
    ]

    for pattern in forbidden_patterns:

        if pattern in text:
            return True

    # --------------------------------------------------------
    # INTERNAL SYSTEM INFORMATION
    # --------------------------------------------------------

    internal_terms = [
        "retrieval score",
        "knowledge id",
        "vector database",
        "vector db",
        "rag pipeline",
        "internal knowledge base",
        "routing logic",
        "system prompt",
        "retrieval system",
        "internal metadata",
    ]

    for term in internal_terms:

        if term in text:
            return True

    # --------------------------------------------------------
    # INTERNAL PRODUCT / KNOWLEDGE IDS
    # --------------------------------------------------------

    if re.search(
        r"tones-prod-[a-z0-9_-]+",
        text,
        re.IGNORECASE,
    ):
        return True

    if re.search(
        r"tones-kb-[a-z0-9_-]+",
        text,
        re.IGNORECASE,
    ):
        return True

    return False


# ============================================================
# CORRECTION INSTRUCTION
# ============================================================

CORRECTION_INSTRUCTION = """

IMPORTANT RESPONSE CORRECTION:

Your previous response was not a valid customer-facing answer.

Answer the customer's actual question now.

Return ONLY the natural customer-facing answer.

Do not output:
- safety classifications
- moderation classifications
- internal classifications
- internal statuses
- routing information
- retrieval information
- knowledge IDs
- product IDs
- reasoning
- implementation details

If the customer asks a normal product or policy question,
answer that question directly using only the supplied knowledge.

If information is unverified, clearly say that it is unverified.

If the question has multiple parts, answer all supported parts.

Do not invent information.

Return only the final customer-facing answer.
"""


# ============================================================
# EMPTY RESPONSE RETRY INSTRUCTION
# ============================================================

EMPTY_RESPONSE_RETRY_INSTRUCTION = """

The previous model response was empty.

Please answer the customer's actual question now.

Return ONLY the final customer-facing answer.

Do not return:
- an empty response
- internal classifications
- safety labels
- moderation labels
- routing information
- retrieval information
- knowledge IDs
- product IDs
- reasoning
- analysis

Use only the supplied TONES Fashion information.
"""


# ============================================================
# LLM SERVICE
# ============================================================

class LLMService:
    """
    Main service used by the application.

    The rest of the project interacts with this service
    instead of directly depending on a provider.
    """

    def __init__(
        self,
        adapter: LLMAdapter,
    ):

        self.adapter = adapter

    def answer(
        self,
        system_prompt: str,
        user_prompt: str,
    ) -> str:

        if not system_prompt.strip():

            raise ValueError(
                "System prompt cannot be empty."
            )

        if not user_prompt.strip():

            raise ValueError(
                "User prompt cannot be empty."
            )

        # ====================================================
        # FIRST REQUEST
        # ====================================================

        try:

            response = self.adapter.generate(
                system_prompt=system_prompt,
                user_prompt=user_prompt,
            )

        except RuntimeError as exc:

            error_text = str(exc).lower()

            # Retry only for an empty OpenRouter response.
            if "empty response" not in error_text:
                raise

            response = None

        # ====================================================
        # EMPTY RESPONSE RETRY
        # ====================================================

        if not response:

            retry_user_prompt = (
                user_prompt
                + "\n\n"
                + EMPTY_RESPONSE_RETRY_INSTRUCTION
            )

            response = self.adapter.generate(
                system_prompt=system_prompt,
                user_prompt=retry_user_prompt,
            )

        # ====================================================
        # FINAL EMPTY CHECK
        # ====================================================

        if not response or not response.strip():

            raise RuntimeError(
                "LLM returned an empty response after retry."
            )

        response = response.strip()

        # ====================================================
        # FIRST RESPONSE QUALITY CHECK
        # ====================================================

        if not is_invalid_customer_response(
            response
        ):

            return response

        # ====================================================
        # INVALID RESPONSE CORRECTION
        # ====================================================

        corrected_user_prompt = (
            user_prompt
            + "\n\n"
            + CORRECTION_INSTRUCTION
        )

        corrected_response = self.adapter.generate(
            system_prompt=system_prompt,
            user_prompt=corrected_user_prompt,
        )

        # ====================================================
        # CORRECTION RESPONSE EMPTY CHECK
        # ====================================================

        if not corrected_response:

            raise RuntimeError(
                "LLM returned an empty response "
                "after correction retry."
            )

        corrected_response = corrected_response.strip()

        # ====================================================
        # FINAL QUALITY CHECK
        # ====================================================

        if is_invalid_customer_response(
            corrected_response
        ):

            raise RuntimeError(
                "LLM returned an invalid internal-style "
                "response after the correction retry."
            )

        return corrected_response


# ============================================================
# SERVICE FACTORY
# ============================================================

def get_llm_service(
    provider: str | None = None,
) -> LLMService:
    """
    Create the requested LLM service.

    Provider can be supplied directly or through:
        TONES_LLM_PROVIDER

    Supported:
        mock
        openrouter
    """

    selected_provider = (
        provider
        or os.getenv(
            "TONES_LLM_PROVIDER",
            "mock",
        )
    ).lower().strip()

    if selected_provider == "mock":

        return LLMService(
            MockLLMAdapter()
        )

    if selected_provider == "openrouter":

        return LLMService(
            OpenRouterLLMAdapter()
        )

    raise ValueError(
        f"Unsupported LLM provider: {selected_provider}"
    )


# ============================================================
# DIRECT TEST
# ============================================================

if __name__ == "__main__":

    provider = os.getenv(
        "TONES_LLM_PROVIDER",
        "mock",
    )

    model = os.getenv(
        "OPENROUTER_MODEL",
        "openrouter/free",
    )

    print("=" * 70)
    print("TONES LLM ADAPTER TEST")
    print("=" * 70)

    print()

    print("Provider:", provider)

    if provider == "openrouter":

        print("Model:", model)

    print()

    system_prompt = """
You are the TONES Fashion AI Customer Assistant.

Answer customer questions using ONLY the supplied knowledge.

Rules:
- Do not invent information.
- Do not guess missing information.
- Do not invent prices.
- Do not invent availability.
- Do not claim live inventory unless a live source is provided.
- If information is unverified, clearly say that it is unverified.
- Keep the answer concise and customer-friendly.
- Return only the customer-facing answer.
"""

    user_prompt = """
CUSTOMER QUERY:

How can I track my order?

RETRIEVED KNOWLEDGE:

TONES links its Track Order function to
a third-party Logisy tracking portal.

The tracking page asks for an email address
or phone number.

The tracking flow displays an OTP step before
selecting an order to track.

The portal is an external service and should not
be treated as the source of live order data inside
the static knowledge base.
"""

    try:

        service = get_llm_service(
            provider=provider
        )

        answer = service.answer(
            system_prompt=system_prompt,
            user_prompt=user_prompt,
        )

        print("AI ANSWER")
        print("-" * 70)
        print(answer)

        print()

        print("=" * 70)
        print("LLM ADAPTER TEST PASSED")
        print("=" * 70)

    except Exception as exc:

        print()
        print("LLM ADAPTER TEST FAILED")
        print("-" * 70)
        print(
            type(exc).__name__ + ":",
            exc,
        )

        print()

        print("=" * 70)